# Generated by Django 5.2.1 on 2025-07-10 09:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('worked_hours', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('hour_9', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_10', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_11', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_12', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_1', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_2', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_3', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_4', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_5', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_6', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
